/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoludo;

import java.awt.Component;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.text.AbstractDocument;


/**
 *
 * @author ricardo
 */
public class Destinos extends javax.swing.JFrame {
    Object[][] datosDestinos;
    String[] columnNames ={"ID destino","Nombre del destino"};
    SQLConn con;
    PreparedStatement pst;
    Principal principal;
    /**
     * Creates new form destinos
     */
    public Destinos(Principal princ) {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sum4.png")));
        this.principal = princ;
        
        try{
            con = new SQLConn();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR FATAL - ERROR AL TRATAR DE CREAR CONECCION A LA BASE DE DATOS","ERROR Principal-SQLCONN",JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        destinos_tbl_desti = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        destinos_btn_add = new javax.swing.JButton();
        destinos_btn_edit = new javax.swing.JButton();
        destinos_btn_limpiar = new javax.swing.JButton();
        destinos_btn_del = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        destinos_jtf_nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        empresas_jtf_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Destinos_btn_regresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Destinos_jtf_buscar = new javax.swing.JTextField();
        Destinos_btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DESTINOS DEL SISTEMA");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        destinos_tbl_desti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        destinos_tbl_desti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destinos_tbl_desti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID destino", "Nombre destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        destinos_tbl_desti.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        destinos_tbl_desti.setSelectionBackground(new java.awt.Color(255, 153, 0));
        destinos_tbl_desti.getTableHeader().setReorderingAllowed(false);
        destinos_tbl_desti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destinos_tbl_destiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(destinos_tbl_desti);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 420, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Administración de destinos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        destinos_btn_add.setBackground(new java.awt.Color(204, 255, 153));
        destinos_btn_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        destinos_btn_add.setForeground(new java.awt.Color(51, 51, 51));
        destinos_btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/add1.png"))); // NOI18N
        destinos_btn_add.setText("Añadir");
        destinos_btn_add.setToolTipText("Añadir empresa");
        destinos_btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        destinos_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinos_btn_addActionPerformed(evt);
            }
        });

        destinos_btn_edit.setBackground(new java.awt.Color(255, 204, 153));
        destinos_btn_edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        destinos_btn_edit.setForeground(new java.awt.Color(51, 51, 51));
        destinos_btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/edit1.png"))); // NOI18N
        destinos_btn_edit.setText("Editar");
        destinos_btn_edit.setToolTipText("Editar empresa");
        destinos_btn_edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        destinos_btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destinos_btn_editMouseClicked(evt);
            }
        });
        destinos_btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinos_btn_editActionPerformed(evt);
            }
        });

        destinos_btn_limpiar.setBackground(new java.awt.Color(204, 204, 204));
        destinos_btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        destinos_btn_limpiar.setForeground(new java.awt.Color(51, 51, 51));
        destinos_btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/clear1.png"))); // NOI18N
        destinos_btn_limpiar.setText("Limpiar");
        destinos_btn_limpiar.setToolTipText("Limpiar los campos");
        destinos_btn_limpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        destinos_btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinos_btn_limpiarActionPerformed(evt);
            }
        });

        destinos_btn_del.setBackground(new java.awt.Color(255, 102, 102));
        destinos_btn_del.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        destinos_btn_del.setForeground(new java.awt.Color(51, 51, 51));
        destinos_btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/delete1.png"))); // NOI18N
        destinos_btn_del.setText("Eliminar");
        destinos_btn_del.setToolTipText("Eliminar empresa");
        destinos_btn_del.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        destinos_btn_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destinos_btn_delMouseClicked(evt);
            }
        });
        destinos_btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinos_btn_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destinos_btn_del, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(destinos_btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destinos_btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(destinos_btn_limpiar)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(destinos_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinos_btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinos_btn_del)
                    .addComponent(destinos_btn_limpiar))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Informacion de destino");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID del destino");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        destinos_jtf_nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(destinos_jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 310, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 10, 80));

        ((AbstractDocument) empresas_jtf_id.getDocument()).setDocumentFilter(new CustomDocumentFilter());
        empresas_jtf_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        empresas_jtf_id.setText("0");
        empresas_jtf_id.setToolTipText("Numero de orden");
        empresas_jtf_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empresas_jtf_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        empresas_jtf_id.setEnabled(false);
        getContentPane().add(empresas_jtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre del destino");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("?");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 20, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Nota 2: Todo cambio que se realice acá no se vera reflejado en los destinos de los registros de suministro ya existentes, para ello se debera cambiar manualmente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        Destinos_btn_regresar.setBackground(new java.awt.Color(255, 153, 0));
        Destinos_btn_regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Destinos_btn_regresar.setText("REGRESAR");
        Destinos_btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destinos_btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(Destinos_btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nota: la ID del destino no se deberia cambiar por este medio, el campo 'ID del destino' solo esta para poder editar otros datos del destino");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        Destinos_jtf_buscar.setToolTipText("Busca un destino");
        Destinos_jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Destinos_jtf_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(Destinos_jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 330, -1));

        Destinos_btn_buscar.setBackground(new java.awt.Color(255, 153, 0));
        Destinos_btn_buscar.setText("BUSCAR");
        getContentPane().add(Destinos_btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpiarCampos(){
        destinos_jtf_nombre.setText("");
        empresas_jtf_id.setText("0");
    }
    private void destinos_btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinos_btn_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_destinos_btn_limpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        update_destinoTable();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        con.desconectar("Destinos");
        principal.start();
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosed

    private void destinos_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinos_btn_addActionPerformed
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
            
        }
        else{
            try{
                pst = con.conn.prepareStatement("INSERT INTO destinos(`nombreDestino`) VALUES(?)");
                pst.setString(1, destinos_jtf_nombre.getText());
                int row = pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Destino añadido correctamente","Agregar destino",JOptionPane.OK_OPTION);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Ocurrio un problema al tratar de agregar un destino","Error - agregar destino",JOptionPane.ERROR_MESSAGE);
                System.out.println("ERROR empresas_btn_addActionPerformed: "+ex.getMessage());
            }
            finally{
                update_destinoTable();
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_destinos_btn_addActionPerformed

    private void destinos_btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinos_btn_editActionPerformed

    }//GEN-LAST:event_destinos_btn_editActionPerformed

    private void destinos_btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinos_btn_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinos_btn_delActionPerformed

    private void destinos_btn_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinos_btn_delMouseClicked
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
        }
        else{
            if(destinos_jtf_nombre.getText().isEmpty() || destinos_jtf_nombre.getText()==""){
            JOptionPane.showMessageDialog(this, "Porfavor escriba o seleccione el nombre del destino a eliminar","Eliminar destino",JOptionPane.OK_OPTION);
            }else{
                String empresaName = destinos_jtf_nombre.getText(); 
                try{
                    pst = con.conn.prepareStatement("SELECT * FROM `destinos` WHERE `nombreDestino`=?");
                    pst.setString(1, empresaName);
                    ResultSet rs = pst.executeQuery();
                    rs.next();
                    int pos = rs.getInt("ID_destino");
                    rs.close();
                    if(pos <=0){
                        JOptionPane.showMessageDialog(this, "Este destino no existe","Eliminar destino",JOptionPane.OK_OPTION);
                    }else{
                        pst = con.conn.prepareStatement("DELETE FROM `destinos` WHERE `nombreDestino`=?");
                        pst.setString(1, empresaName);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Destino eliminado correctamente","Eliminar destino",JOptionPane.OK_OPTION);
                    }
                    
                }catch(SQLException ex){
                    System.out.println("ERROR ELIMINAR DESTINO: "+ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de eliminar el destino","Eliminar destino",JOptionPane.ERROR_MESSAGE);
                }finally{
                    update_destinoTable();
                    limpiarCampos();
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_destinos_btn_delMouseClicked

    private void destinos_tbl_destiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinos_tbl_destiMouseClicked
        DefaultTableModel model = (DefaultTableModel)destinos_tbl_desti.getModel();
        int myIndex = destinos_tbl_desti.getSelectedRow();
        destinos_jtf_nombre.setText(model.getValueAt(myIndex, 1).toString());
        empresas_jtf_id.setText(model.getValueAt(myIndex, 0).toString());
    }//GEN-LAST:event_destinos_tbl_destiMouseClicked

    private void destinos_btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinos_btn_editMouseClicked
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
        }
        else{
            if(destinos_jtf_nombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Porfavor introduzca un valor a editar","Editar destino",JOptionPane.OK_OPTION);
            }else{
                String nombreEmpresa = destinos_jtf_nombre.getText();
                int idEmpresa = Integer.valueOf(empresas_jtf_id.getText());
                try{
                    
                    pst = con.conn.prepareStatement("UPDATE `destinos` SET `nombreDestino`=? WHERE `ID_destino`=?");
                    pst.setString(1, nombreEmpresa);
                    pst.setInt(2, idEmpresa);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Destino editado correctamente","Editar destino",JOptionPane.OK_OPTION);
                }catch(SQLException ex){
                    System.out.println("ERROR EDITAR DESTINO: "+ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de editar un destino","Editar destino",JOptionPane.ERROR_MESSAGE);       
                }finally{
                    update_destinoTable();
                    limpiarCampos();
                }
            }
        }
        
    }//GEN-LAST:event_destinos_btn_editMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JOptionPane.showMessageDialog(this, "*Al añadir un nuevo destino se le colocara una ID establecida por el sistema.\n*Al editar un destino, el campo de 'ID' debe contener una ID existente.\n*Ni la ID ni el nombre del destino se puede repetir.","INFORMACION DESTINOS",JOptionPane.INFORMATION_MESSAGE);       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void Destinos_btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destinos_btn_regresarActionPerformed

        this.dispose();
    }//GEN-LAST:event_Destinos_btn_regresarActionPerformed

    private void Destinos_jtf_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Destinos_jtf_buscarKeyReleased
        int valor = 0;
        int cont = 0;
        String aux = "" + Destinos_jtf_buscar.getText();
        try{
            Statement at_count = con.getConnection().createStatement();
            ResultSet res = pst.executeQuery("SELECT COUNT(*) FROM destinos WHERE nombreDestino LIKE'"+Destinos_jtf_buscar.getText()+"%'");
            
            if(res.next()){
                valor = res.getInt(1);
            }
            datosDestinos = new String[valor][2];
            res = pst.executeQuery("SELECT * FROM destinos WHERE nombreDestino LIKE'" + Destinos_jtf_buscar.getText() + "%' ORDER BY ID_destino ASC");
            while(res.next()){
                datosDestinos[cont][0] = res.getString("ID_destino");
                datosDestinos[cont][1] = res.getString("nombreDestino");
                cont++;
            }
            DefaultTableModel tm_datos = new DefaultTableModel(datosDestinos,columnNames){
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }};
            destinos_tbl_desti.setModel(tm_datos);
            
            
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_Destinos_jtf_buscarKeyReleased
   public void clearTable(){
        ((DefaultTableModel)destinos_tbl_desti.getModel()).setRowCount(0);
    }    
    public void update_destinoTable(){
        clearTable();
        
        
        datosDestinos = getDestinosDatos();
        DefaultTableModel tm_datos = new DefaultTableModel(datosDestinos,columnNames){
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        destinos_tbl_desti.setModel(tm_datos);
        
        final TableColumnModel columnModel = destinos_tbl_desti.getColumnModel();
        for (int column = 0; column < destinos_tbl_desti.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < destinos_tbl_desti.getRowCount(); row++) {
                TableCellRenderer renderer = destinos_tbl_desti.getCellRenderer(row, column);
                Component comp = destinos_tbl_desti.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            if(width > 300)
                width=300;
            columnModel.getColumn(column).setPreferredWidth(width);
        }
        
        //TableRowSorter trs = new TableRowSorter<>(tm_datos);
        //destinos_tbl_desti.setRowSorter(trs);

    }

public Object [][] getDestinosDatos(){
        
        int registros = 0;
        
        try{
            pst = con.conn.prepareStatement("SELECT count(1) as total FROM destinos");
            ResultSet res = pst.executeQuery();
            res.next();
            registros = res.getInt("total");
            res.close();
            
        }catch(SQLException ex){
            System.out.println(ex);
        }
        Object[][] data = new Object[registros][2];
        try{

            pst = con.conn.prepareStatement("SELECT"+" ID_destino, nombreDestino"+" FROM destinos ORDER BY ID_destino");
            ResultSet res = pst.executeQuery();
            int i = 0;
            while(res.next()){
                int idDestino = Integer.parseInt(res.getString("ID_destino"));
                String nombreDestino = res.getString("nombreDestino");

                data[i][0] = idDestino;
                data[i][1] = nombreDestino;
                i++;
            }
            res.close();
        }catch(SQLException ex){
            System.out.println(ex);
        }
        return data;
    }
    /**
     * @param args the command line arguments
     */
    public void start(){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destinos(principal).setVisible(true);
            }
        });
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Destinos(principal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Destinos_btn_buscar;
    private javax.swing.JButton Destinos_btn_regresar;
    private javax.swing.JTextField Destinos_jtf_buscar;
    private javax.swing.JButton destinos_btn_add;
    private javax.swing.JButton destinos_btn_del;
    private javax.swing.JButton destinos_btn_edit;
    private javax.swing.JButton destinos_btn_limpiar;
    private javax.swing.JTextField destinos_jtf_nombre;
    private javax.swing.JTable destinos_tbl_desti;
    private javax.swing.JTextField empresas_jtf_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
