/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoludo;

import java.awt.Component;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.text.AbstractDocument;


/**
 *
 * @author ricardo
 */
public class Empresas extends javax.swing.JFrame {
    SQLConn con;
    PreparedStatement pst;
    Principal principal;

    /**
     * Creates new form empresas
     */
    public Empresas(Principal princ) {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sum4.png")));
        this.principal = princ;
        
        try{
            con = new SQLConn();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR FATAL - ERROR AL TRATAR DE CREAR CONECCION A LA BASE DE DATOS","ERROR Principal-SQLCONN",JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        empresas_tbl_empre = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        empresas_btn_add = new javax.swing.JButton();
        empresas_btn_edit = new javax.swing.JButton();
        empresas_btn_limpiar = new javax.swing.JButton();
        empresas_btn_del = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        empresas_jtf_nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        empresas_jtf_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EMPRESAS DEL SISTEMA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empresas_tbl_empre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empresas_tbl_empre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empresas_tbl_empre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID empresa", "Nombre Empresa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empresas_tbl_empre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        empresas_tbl_empre.setSelectionBackground(new java.awt.Color(255, 153, 0));
        empresas_tbl_empre.getTableHeader().setReorderingAllowed(false);
        empresas_tbl_empre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empresas_tbl_empreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(empresas_tbl_empre);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 48, 420, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Administración de empresas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        empresas_btn_add.setBackground(new java.awt.Color(204, 255, 153));
        empresas_btn_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empresas_btn_add.setForeground(new java.awt.Color(51, 51, 51));
        empresas_btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/add1.png"))); // NOI18N
        empresas_btn_add.setText("Añadir");
        empresas_btn_add.setToolTipText("Añadir empresa");
        empresas_btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empresas_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresas_btn_addActionPerformed(evt);
            }
        });

        empresas_btn_edit.setBackground(new java.awt.Color(255, 204, 153));
        empresas_btn_edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empresas_btn_edit.setForeground(new java.awt.Color(51, 51, 51));
        empresas_btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/edit1.png"))); // NOI18N
        empresas_btn_edit.setText("Editar");
        empresas_btn_edit.setToolTipText("Editar empresa");
        empresas_btn_edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empresas_btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empresas_btn_editMouseClicked(evt);
            }
        });
        empresas_btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresas_btn_editActionPerformed(evt);
            }
        });

        empresas_btn_limpiar.setBackground(new java.awt.Color(204, 204, 204));
        empresas_btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empresas_btn_limpiar.setForeground(new java.awt.Color(51, 51, 51));
        empresas_btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/clear1.png"))); // NOI18N
        empresas_btn_limpiar.setText("Limpiar");
        empresas_btn_limpiar.setToolTipText("Limpiar los campos");
        empresas_btn_limpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empresas_btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresas_btn_limpiarActionPerformed(evt);
            }
        });

        empresas_btn_del.setBackground(new java.awt.Color(255, 102, 102));
        empresas_btn_del.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empresas_btn_del.setForeground(new java.awt.Color(51, 51, 51));
        empresas_btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/delete1.png"))); // NOI18N
        empresas_btn_del.setText("Eliminar");
        empresas_btn_del.setToolTipText("Eliminar empresa");
        empresas_btn_del.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empresas_btn_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empresas_btn_delMouseClicked(evt);
            }
        });
        empresas_btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresas_btn_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empresas_btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empresas_btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(empresas_btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(empresas_btn_limpiar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empresas_btn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empresas_btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresas_btn_del)
                    .addComponent(empresas_btn_limpiar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 210, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Informacion de empresa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID de la empresa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        empresas_jtf_nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(empresas_jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 310, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 10, 80));

        ((AbstractDocument) empresas_jtf_id.getDocument()).setDocumentFilter(new CustomDocumentFilter());
        empresas_jtf_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        empresas_jtf_id.setText("0");
        empresas_jtf_id.setToolTipText("Numero de orden");
        empresas_jtf_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        empresas_jtf_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        empresas_jtf_id.setEnabled(false);
        getContentPane().add(empresas_jtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre de la empresa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("?");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 20, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nota: la ID de la empresa no se podra cambiar por este medio, el campo 'ID de la empresa' solo esta para poder editar otros datos de la empresa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpiarCampos(){
        empresas_jtf_nombre.setText("");
        empresas_jtf_id.setText("0");
    }
    private void empresas_btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresas_btn_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_empresas_btn_limpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        update_empresaTable();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        con.desconectar("Empresas");
        principal.start();
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosed

    private void empresas_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresas_btn_addActionPerformed
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
            
        }
        else{
            try{
                pst = con.conn.prepareStatement("INSERT INTO empresas(`nombreEmpresa`) VALUES(?)");
                pst.setString(1, empresas_jtf_nombre.getText());
                int row = pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Empresa añadida correctamente","Agregar empresa",JOptionPane.OK_OPTION);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Ocurrio un problema al tratar de agregar una empresa","Error - agregar empresa",JOptionPane.ERROR_MESSAGE);
                System.out.println(ex.getMessage());
            }
            finally{
                update_empresaTable();
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_empresas_btn_addActionPerformed

    private void empresas_btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresas_btn_editActionPerformed

    }//GEN-LAST:event_empresas_btn_editActionPerformed

    private void empresas_btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresas_btn_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresas_btn_delActionPerformed

    private void empresas_btn_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empresas_btn_delMouseClicked
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
        }
        else{
            if(empresas_jtf_nombre.getText().isEmpty() || empresas_jtf_nombre.getText()==""){
            JOptionPane.showMessageDialog(this, "Porfavor escriba o seleccione el nombre de la empresa a eliminar","Eliminar empresa",JOptionPane.OK_OPTION);
            }else{
                String empresaName = empresas_jtf_nombre.getText(); 
                try{
                    pst = con.conn.prepareStatement("SELECT * FROM `empresas` WHERE `nombreEmpresa`=?");
                    pst.setString(1, empresaName);
                    ResultSet rs = pst.executeQuery();
                    rs.next();
                    int pos = rs.getInt("ID_empresa");
                    rs.close();
                    if(pos <=0){
                        JOptionPane.showMessageDialog(this, "Esta empresa no existe","Eliminar empresa",JOptionPane.OK_OPTION);
                    }else{
                        pst = con.conn.prepareStatement("DELETE FROM `empresas` WHERE `nombreEmpresa`=?");
                        pst.setString(1, empresaName);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Empresa eliminada correctamente","Eliminar empresa",JOptionPane.OK_OPTION);
                    }
                    
                }catch(SQLException ex){
                    System.out.println("ERROR ELIMINAR EMPRESA: "+ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de eliminar la empresa","Eliminar empresa",JOptionPane.ERROR_MESSAGE);
                }finally{
                    update_empresaTable();
                    limpiarCampos();
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_empresas_btn_delMouseClicked

    private void empresas_tbl_empreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empresas_tbl_empreMouseClicked
        DefaultTableModel model = (DefaultTableModel)empresas_tbl_empre.getModel();
        int myIndex = empresas_tbl_empre.getSelectedRow();
        empresas_jtf_nombre.setText(model.getValueAt(myIndex, 1).toString());
        empresas_jtf_id.setText(model.getValueAt(myIndex, 0).toString());
    }//GEN-LAST:event_empresas_tbl_empreMouseClicked

    private void empresas_btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empresas_btn_editMouseClicked
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
        }
        else{
            if(empresas_jtf_nombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Porfavor introduzca un valor a editar","Editar empresa",JOptionPane.OK_OPTION);
            }else{
                String nombreEmpresa = empresas_jtf_nombre.getText();
                int idEmpresa = Integer.valueOf(empresas_jtf_id.getText());
                try{
                    
                    pst = con.conn.prepareStatement("UPDATE `empresas` SET `nombreEmpresa`=? WHERE `ID_empresa`=?");
                    pst.setString(1, nombreEmpresa);
                    pst.setInt(2, idEmpresa);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Empresa editada correctamente","Editar empresa",JOptionPane.OK_OPTION);
                }catch(SQLException ex){
                    System.out.println("ERROR EDITAR EMPRESA: "+ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de editar una empresa","Editar empresa",JOptionPane.ERROR_MESSAGE);       
                }finally{
                    update_empresaTable();
                    limpiarCampos();
                }
            }
        }
        
    }//GEN-LAST:event_empresas_btn_editMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JOptionPane.showMessageDialog(this, "*Al añadir una nueva empresa se le colocara una ID establecida por el sistema.\n*Al editar una empresa el campo de 'ID' debe contener una ID existente.\n*Ni la ID ni el nombre de la empresa se puede repetir.","INFORMACION EMPRESAS",JOptionPane.INFORMATION_MESSAGE);       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   public void clearTable(){
        ((DefaultTableModel)empresas_tbl_empre.getModel()).setRowCount(0);
    }    
    public void update_empresaTable(){
        clearTable();
        Object[][] dtPer;
        String[] columnNames ={"ID empresa","Nombre de la empresa"};
        dtPer = getEmpresasDatos();
        DefaultTableModel datos = new DefaultTableModel(dtPer,columnNames){
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        empresas_tbl_empre.setModel(datos);
        final TableColumnModel columnModel = empresas_tbl_empre.getColumnModel();
        for (int column = 0; column < empresas_tbl_empre.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < empresas_tbl_empre.getRowCount(); row++) {
                TableCellRenderer renderer = empresas_tbl_empre.getCellRenderer(row, column);
                Component comp = empresas_tbl_empre.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            if(width > 300)
                width=300;
            columnModel.getColumn(column).setPreferredWidth(width);
        }

    }

public Object [][] getEmpresasDatos(){
        
        int registros = 0;
        
        try{
            pst = con.conn.prepareStatement("SELECT count(1) as total FROM empresas");
            ResultSet res = pst.executeQuery();
            res.next();
            registros = res.getInt("total");
            res.close();
            
        }catch(SQLException ex){
            System.out.println(ex);
        }
        Object[][] data = new String[registros][2];
        try{

            pst = con.conn.prepareStatement("SELECT"+" ID_empresa, nombreEmpresa"+" FROM empresas ORDER BY ID_empresa");
            ResultSet res = pst.executeQuery();
            int i = 0;
            while(res.next()){
                String idEmpresa = res.getString("ID_empresa");
                String nombreEmpresa = res.getString("nombreEmpresa");

                data[i][0] = idEmpresa;
                data[i][1] = nombreEmpresa;
                i++;
            }
            res.close();
        }catch(SQLException ex){
            System.out.println(ex);
        }
        return data;
    }
    /**
     * @param args the command line arguments
     */
    public void start(){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresas(principal).setVisible(true);
            }
        });
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Empresas(principal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empresas_btn_add;
    private javax.swing.JButton empresas_btn_del;
    private javax.swing.JButton empresas_btn_edit;
    private javax.swing.JButton empresas_btn_limpiar;
    private javax.swing.JTextField empresas_jtf_id;
    private javax.swing.JTextField empresas_jtf_nombre;
    private javax.swing.JTable empresas_tbl_empre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
