/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoludo;

import java.awt.Component;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.text.AbstractDocument;
import org.apache.commons.dbutils.DbUtils;


/**
 *
 * @author ricardo
 */
public class Productos extends javax.swing.JFrame {
    SQLConn con;
    PreparedStatement pst;

    /**
     * Creates new form destinos
     */
    public Productos() {
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sum4.png")));
        try{
            con = new SQLConn();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR FATAL - ERROR AL TRATAR DE CREAR CONECCION A LA BASE DE DATOS","ERROR Productos-SQLCONN",JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productos_tbl_desti = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        productos_btn_add = new javax.swing.JButton();
        productos_btn_edit = new javax.swing.JButton();
        productos_btn_limpiar = new javax.swing.JButton();
        productos_btn_del = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productos_jtf_nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        productos_jtf_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        productos_jtf_tipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRODUCTOS DEL SISTEMA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos_tbl_desti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productos_tbl_desti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productos_tbl_desti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID producto", "Nombre producto", "Tipo producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productos_tbl_desti.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productos_tbl_desti.setSelectionBackground(new java.awt.Color(255, 153, 0));
        productos_tbl_desti.getTableHeader().setReorderingAllowed(false);
        productos_tbl_desti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productos_tbl_destiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productos_tbl_desti);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 420, 370));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Administración de Productos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        productos_btn_add.setBackground(new java.awt.Color(204, 255, 153));
        productos_btn_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productos_btn_add.setForeground(new java.awt.Color(51, 51, 51));
        productos_btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/add1.png"))); // NOI18N
        productos_btn_add.setText("Añadir");
        productos_btn_add.setToolTipText("Añadir empresa");
        productos_btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productos_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productos_btn_addActionPerformed(evt);
            }
        });

        productos_btn_edit.setBackground(new java.awt.Color(255, 204, 153));
        productos_btn_edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productos_btn_edit.setForeground(new java.awt.Color(51, 51, 51));
        productos_btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/edit1.png"))); // NOI18N
        productos_btn_edit.setText("Editar");
        productos_btn_edit.setToolTipText("Editar empresa");
        productos_btn_edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productos_btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productos_btn_editMouseClicked(evt);
            }
        });
        productos_btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productos_btn_editActionPerformed(evt);
            }
        });

        productos_btn_limpiar.setBackground(new java.awt.Color(204, 204, 204));
        productos_btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productos_btn_limpiar.setForeground(new java.awt.Color(51, 51, 51));
        productos_btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/clear1.png"))); // NOI18N
        productos_btn_limpiar.setText("Limpiar");
        productos_btn_limpiar.setToolTipText("Limpiar los campos");
        productos_btn_limpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productos_btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productos_btn_limpiarActionPerformed(evt);
            }
        });

        productos_btn_del.setBackground(new java.awt.Color(255, 102, 102));
        productos_btn_del.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productos_btn_del.setForeground(new java.awt.Color(51, 51, 51));
        productos_btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/delete1.png"))); // NOI18N
        productos_btn_del.setText("Eliminar");
        productos_btn_del.setToolTipText("Eliminar empresa");
        productos_btn_del.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productos_btn_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productos_btn_delMouseClicked(evt);
            }
        });
        productos_btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productos_btn_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productos_btn_del, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(productos_btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productos_btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productos_btn_limpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productos_btn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productos_btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productos_btn_del)
                    .addComponent(productos_btn_limpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 210, 140));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Informacion de producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID del producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        productos_jtf_nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(productos_jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 10, 80));

        ((AbstractDocument) productos_jtf_id.getDocument()).setDocumentFilter(new CustomDocumentFilter());
        productos_jtf_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        productos_jtf_id.setText("0");
        productos_jtf_id.setToolTipText("Numero de orden");
        productos_jtf_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        productos_jtf_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        productos_jtf_id.setEnabled(false);
        getContentPane().add(productos_jtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre del producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("?");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 20, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nota: la ID del producto no se deberia cambiar por este medio, el campo 'ID del producto' solo esta para poder editar otros datos del producto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        productos_jtf_tipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(productos_jtf_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tipo de producto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpiarCampos(){
        productos_jtf_nombre.setText("");
        productos_jtf_id.setText("0");
        productos_jtf_tipo.setText("");
    }
    private void productos_btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productos_btn_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_productos_btn_limpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        update_productosTable();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        
        try{
            con.desconectar("Productos");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error","ERROR Productos-SQLCONN",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosed

    private void productos_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productos_btn_addActionPerformed
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
            
        }
        else{
            if(productos_jtf_nombre.getText().isEmpty() || productos_jtf_nombre.getText() == ""){
                JOptionPane.showMessageDialog(null, "El campo de nombre no puede estar vacio","Error - agregar producto",JOptionPane.WARNING_MESSAGE);
            }else{
                try{
                pst = con.conn.prepareStatement("INSERT INTO productos(`nombreProd`,`tipoProducto`) VALUES(?,?)");
                
                pst.setString(1, productos_jtf_nombre.getText());
                pst.setString(2, productos_jtf_tipo.getText());
                int row = pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Producto añadido correctamente","Agregar producto",JOptionPane.OK_OPTION);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema al tratar de agregar un producto","Error - agregar producto",JOptionPane.ERROR_MESSAGE);
                    System.out.println("ERROR productos_btn_addActionPerformed: "+ex.getMessage());
                }
                finally{
                    update_productosTable();
                    limpiarCampos();
                }
            }
            
        }
    }//GEN-LAST:event_productos_btn_addActionPerformed

    private void productos_btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productos_btn_editActionPerformed

    }//GEN-LAST:event_productos_btn_editActionPerformed

    private void productos_btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productos_btn_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productos_btn_delActionPerformed

    private void productos_btn_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_btn_delMouseClicked
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
        }
        else{
            if(productos_jtf_id.getText().isEmpty() || productos_jtf_id.getText()=="0"){
            JOptionPane.showMessageDialog(this, "Porfavor escriba o seleccione el nombre del producto a eliminar","Eliminar producto",JOptionPane.OK_OPTION);
            }else{
                //String empresaName = productos_jtf_nombre.getText(); 
                try{
                    pst = con.conn.prepareStatement("SELECT * FROM `productos` WHERE `ID_producto`=?");
                    pst.setString(1, productos_jtf_id.getText());
                    ResultSet rs = pst.executeQuery();
                    rs.next();
                    int pos = rs.getInt("ID_producto");
                    rs.close();
                    if(pos <=0){
                        JOptionPane.showMessageDialog(this, "Este producto no existe","Eliminar producto",JOptionPane.OK_OPTION);
                    }else{
                        pst = con.conn.prepareStatement("DELETE FROM `productos` WHERE `ID_producto`=?");
                        pst.setString(1, productos_jtf_id.getText());
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Producto eliminado correctamente","Eliminar producto",JOptionPane.OK_OPTION);
                    }
                    
                }catch(SQLException ex){
                    System.out.println("ERROR ELIMINAR PRODUCTO: "+ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de eliminar el producto","Eliminar producto",JOptionPane.ERROR_MESSAGE);
                }finally{
                    update_productosTable();
                    limpiarCampos();
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_productos_btn_delMouseClicked

    private void productos_tbl_destiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_tbl_destiMouseClicked
        try{
            DefaultTableModel model = (DefaultTableModel)productos_tbl_desti.getModel();
            int myIndex = productos_tbl_desti.getSelectedRow();
            productos_jtf_nombre.setText(model.getValueAt(myIndex, 1).toString());
            productos_jtf_id.setText(model.getValueAt(myIndex, 0).toString());
            productos_jtf_tipo.setText(model.getValueAt(myIndex,2).toString());
        }catch(Exception ex){
            System.out.println("productos_tbl_destiMouseClicked: "+ex.getMessage());
        }
        
    }//GEN-LAST:event_productos_tbl_destiMouseClicked

    private void productos_btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_btn_editMouseClicked
        if(User.Rank <2){
            JOptionPane.showMessageDialog(null, "No tienes permiso para realizar esta accion","Informacion",JOptionPane.OK_OPTION);
        }
        else{
            if(productos_jtf_nombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Porfavor introduzca un valor a editar","Editar producto",JOptionPane.OK_OPTION);
            }else{
                String nombreProducto = productos_jtf_nombre.getText();
                int idProducto = Integer.valueOf(productos_jtf_id.getText());
                String tipoProducto = productos_jtf_tipo.getText();
                try{
                    
                    pst = con.conn.prepareStatement("UPDATE `productos` SET `nombreProd`=?, `tipoProducto`=? WHERE `ID_producto`=?");
                    pst.setString(1, nombreProducto);
                    pst.setString(2, tipoProducto);
                    pst.setInt(3, idProducto);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Producto editado correctamente","Editar producto",JOptionPane.OK_OPTION);
                }catch(SQLException ex){
                    System.out.println("ERROR EDITAR PRODUCTO: "+ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de editar un producto","Editar producto",JOptionPane.ERROR_MESSAGE);       
                }finally{
                    update_productosTable();
                    limpiarCampos();
                }
            }
        }
        
    }//GEN-LAST:event_productos_btn_editMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JOptionPane.showMessageDialog(this, "*Al añadir un nuevo producto se le colocara una ID establecida por el sistema.\n*Al editar un producto, el campo de 'ID' debe contener una ID existente.\n*Ni la ID ni el nombre del producto se puede repetir.","INFORMACION PRODUCTOS",JOptionPane.INFORMATION_MESSAGE);       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Principal principal = new Principal();
        principal.start();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   public void clearTable(){
        ((DefaultTableModel)productos_tbl_desti.getModel()).setRowCount(0);
    }    
    public void update_productosTable(){
        clearTable();
        Object[][] dtPer;
        String[] columnNames ={"ID producto","Nombre del producto", "Tipo producto"};
        dtPer = getProductosDatos();
        DefaultTableModel datos = new DefaultTableModel(dtPer,columnNames){
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        productos_tbl_desti.setModel(datos);
        final TableColumnModel columnModel = productos_tbl_desti.getColumnModel();
        for (int column = 0; column < productos_tbl_desti.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < productos_tbl_desti.getRowCount(); row++) {
                TableCellRenderer renderer = productos_tbl_desti.getCellRenderer(row, column);
                Component comp = productos_tbl_desti.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            if(width > 300)
                width=300;
            columnModel.getColumn(column).setPreferredWidth(width);
        }

    }

public Object [][] getProductosDatos(){
        
        int registros = 0;
        
        try{
            pst = con.conn.prepareStatement("SELECT count(1) as total FROM productos");
            ResultSet res = pst.executeQuery();
            res.next();
            registros = res.getInt("total");
            res.close();
            
        }catch(SQLException ex){
            System.out.println(ex);
        }
        Object[][] data = new String[registros][3];
        try{

            pst = con.conn.prepareStatement("SELECT"+" ID_producto, nombreProd, tipoProducto"+" FROM productos ORDER BY ID_producto");
            ResultSet res = pst.executeQuery();
            int i = 0;
            while(res.next()){
                String idProducto = res.getString("ID_producto");
                String nombreProducto = res.getString("nombreProd");
                String tipoProducto = res.getString("tipoProducto");

                data[i][0] = idProducto;
                data[i][1] = nombreProducto;
                data[i][2] = tipoProducto;
                i++;
            }
            res.close();
        }catch(SQLException ex){
           
            System.out.println("ERROR getProductosDatos(): "+ex);
        }
        return data;
    }
    /**
     * @param args the command line arguments
     */
    public void start(){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton productos_btn_add;
    private javax.swing.JButton productos_btn_del;
    private javax.swing.JButton productos_btn_edit;
    private javax.swing.JButton productos_btn_limpiar;
    private javax.swing.JTextField productos_jtf_id;
    private javax.swing.JTextField productos_jtf_nombre;
    private javax.swing.JTextField productos_jtf_tipo;
    private javax.swing.JTable productos_tbl_desti;
    // End of variables declaration//GEN-END:variables
}
