/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoludo;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author ricardo
 */
public class SysLogin extends javax.swing.JFrame {

    /**
     * Creates new form SysLogin
     */
    CustomLogger logger = CustomLogger.getInstance();
    SQLConn con;
    PreparedStatement pst;
    public SysLogin() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sum4.png")));
        try{
            con = new SQLConn();
        }catch(Exception ex){
            System.out.println("Error Login-SQLCONN:"+ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error al tratar de conectar a la base de datos","ERROR Login-SQLCONN",JOptionPane.WARNING_MESSAGE);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        login_jtf_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login_jtf_user = new javax.swing.JTextField();
        login_btn_enter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesion al Sistema de Suministros");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_jtf_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_jtf_pass.setToolTipText("Contraseña de usuario");
        login_jtf_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(login_jtf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 204, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        login_jtf_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_jtf_user.setToolTipText("Nombre de usuario");
        login_jtf_user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        login_jtf_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jtf_userActionPerformed(evt);
            }
        });
        jPanel2.add(login_jtf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 204, -1));

        login_btn_enter.setBackground(new java.awt.Color(255, 153, 0));
        login_btn_enter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_btn_enter.setForeground(new java.awt.Color(51, 51, 51));
        login_btn_enter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/key1.png"))); // NOI18N
        login_btn_enter.setText("Entrar");
        login_btn_enter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        login_btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btn_enterActionPerformed(evt);
            }
        });
        jPanel2.add(login_btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Inicio de sesión para el sistema");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoludo/sum.PNG"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Proyecto Informatica Ludovico Silva - Maturín");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sistema de manejo de suministros - V-1.6.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_jtf_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jtf_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_jtf_userActionPerformed

    private void login_btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btn_enterActionPerformed
        boolean status = false;
        int user_id = -1;
        int user_rank = -1;
        int totalUsers = -1;
        String rankName = "NULL";

        try{

            pst = con.conn.prepareStatement("SELECT count(1) as total FROM usuarios");
            ResultSet res = pst.executeQuery();
            res.next();
            totalUsers = res.getInt("total");
            res.close();
            pst = con.conn.prepareStatement("SELECT ID_usuario, rank, nombreRank FROM usuarios as u JOIN userranks as r ON u.rank=r.ID_rank WHERE username=? AND password=?");
            pst.setString(1, login_jtf_user.getText());
            pst.setString(2, login_jtf_pass.getText());
            res = pst.executeQuery();
            status = res.next();
            user_id = res.getInt("ID_usuario");
            user_rank = res.getInt("rank");
            rankName = res.getString("nombreRank");
            res.close();
        }catch(Exception ex){
            System.out.println("ERROR: "+ex.getMessage());
            JOptionPane.showMessageDialog(null,"Nombre de usuario o contraseña incorrecta","ERROR INICIO SESION",JOptionPane.ERROR_MESSAGE);
        }
        try{
            if (status){
                
                User.Username = login_jtf_user.getText();
                User.ID = user_id;
                User.totalUsers = totalUsers;
                User.Rank = user_rank;
                User.rankName = rankName;
                
                String info = "Usuario '"+login_jtf_user.getText()+"' entro al sistema.";
                //logger.register(info);
                //logger.read();
                JOptionPane.showMessageDialog(null, "Bienvenido "+login_jtf_user.getText(),"Exito al iniciar sesión",JOptionPane.INFORMATION_MESSAGE);
                try{
                    //Principal principal = new Principal();
                    //principal.start();
                    PostLogin postlogin = new PostLogin();
                    postlogin.start();
                    this.dispose();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al tratar de acceder a la ventana principal","ERROR ACCESO A PRINCIPAL",JOptionPane.OK_OPTION);
                }
                
            }
        }catch(Exception ex){
            System.out.println("ERROR EN SYSLOGIN: "+ex);
            JOptionPane.showMessageDialog(null, "No existe un usuario que coincida con el nombre de usuario y la contraseña introducida","Nombre de usuario o contraseña incorrecta",JOptionPane.OK_OPTION);
        }
        
    }//GEN-LAST:event_login_btn_enterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        con.desconectar("SysLogin");
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    
    public static void start(){
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysLogin().setVisible(true);
            }
        });
    } 
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_btn_enter;
    private javax.swing.JPasswordField login_jtf_pass;
    private javax.swing.JTextField login_jtf_user;
    // End of variables declaration//GEN-END:variables
}
